### ISSUE TITLE
Support for Berks

### ISSUE THREAD

**Issue by naumchenko** [sensu/sensu-chef#378]
How complex it is to move this one to Berks? instead librarian?
Berks now shipped with Chef-DK, installing librarian gems messing up chef-dk's ones.

Cheers,

**Comment by luckymike** [comment]
Hi @naumchenko, support for using Berks locally is merged, but not yet released, please see issue #370.

This repository includes a Gemfile so that all the development & testing dependencies may be installed correctly using the bundler gem (see more on this in issue #369). We've made this decision very consciously. 

Bundler allows us to ensure that the correct dependencies are installed, which improves the user experience when working with this cookbook locally, and our ability to respond effectively to reported issues. Because ChefDK is an externally installed package, we have no way of knowing which version the user has installed, or if it is installed at all. Without that knowledge, it is very difficult to troubleshoot issues that folks report, as we cannot reliably replicate the operating environment.

I hope this clarifies our decision here, and provides the resources you need to use Berks locally.
