### ISSUE TITLE
remove unless to allow zap cookbook to control checks directory

### ISSUE THREAD

**Issue by Koen76** [sensu/sensu-chef#388]
Please remove the unless statement in the json provider to allow zap cookbook have control over the checks directory. Zap is perfectly capable to keep the directory in sync with your checks created bij the checks provider, but the unless statement should be removed for this.

This is the code blok in the json provider:
  unless Sensu::JSONFile.compare_content(new_resource.path, new_resource.content)
    directory ::File.dirname(new_resource.path) do
      recursive true
      owner @owner
      group new_resource.group
      mode 0750
    end

    f = file new_resource.path do
      owner @owner
      group new_resource.group
      mode new_resource.mode
      content Sensu::JSONFile.dump_json(new_resource.content)
      notifies :create, "ruby_block[sensu_service_trigger]", :delayed if sensu_service_trigger
    end

    new_resource.updated_by_last_action(f.updated_by_last_action?)
  end
end

Please remove unless and add zap control over checks directory

**Comment by cwjohnston** [comment]
@Koen76 because we are hesitant to change behavior in a way that might impact existing uses, we need a little more information about your request before we can take any action. Would moving the `directory` resource outside of this `unless` block have the desired effect?

@portertech is there a reason we depend on `Sensu::JSONFile.compare_content` to do content comparison instead of depending on Chef's `file` provider to do the right thing?
