### ISSUE TITLE
Drop Chef 11 support in next major release?

### ISSUE THREAD

**Issue by luckymike** [sensu/sensu-chef#425]
For forward compatibility , we will need to replace the deprecated `windows_package` resource soon. This will have the effect of breaking the cookbook for Chef 11. Is this appropriate in our next major release?

**Comment by jtimberman** [comment]
Generally speaking it's acceptable to break chef version compatibility in a cookbook's major release. The reason is because users can always pin to an older version of the cookbook. They won't get new features, or possibly bug fixes, but they also don't get those benefits from staying on an old version of chef itself.

For what it's worth, chef 12 was released on December 5, 2014. The last release of a Chef 11 was April 30, 2015, 11.18.2.

**Comment by cwjohnston** [comment]
My own curiosity has lead me to test the change proposed in #468 on Chef 11. In attempting to do so, I've found that a number of cookbooks we have open-ended dependencies on can no longer be used with Chef 11 due to dependency on the compat_resource cookbook.

Given the reasons cited by others in this thread, and given that its getting more and more involved to test on Chef 11 (our current kitchen.yml doesn't implement that testing anyway), I'm 👍  on dropping Chef 11 support in 3.0.0.

**Comment by cwjohnston** [comment]
Readme changes in #470 document that we no longer actively support Chef 11.
