### ISSUE TITLE
Log level is not set correctly when init_style as "runit"; always use default "info" log level

### ISSUE THREAD

**Issue by JibinZheng** [sensu/sensu-chef#484]
Log level is not set correctly when init_style is set as "runit"; always uses default "info" log level; when init_style is set as "sysv", log level is set correctly.
## Expected Behavior

"-L log_level" should be also passed to the command when init_style is set as "runit"
## Current Behavior

"-L log_level" is not passed to the command when init_style is set as "runit"
## Steps to Reproduce (for bugs)

1. Set the log_level to "warn" and init_style to "runit" or "sysv" in the chef cookbook
2. After converge, run ps -ef | grep sensu

default["sensu"]["log_level"] = "warn"
default["sensu"]["init_style"] = "runit" 

sensu     3268  3245  1 22:03 ?        00:00:00 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-server -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu-server.log

default["sensu"]["log_level"] = "warn"
default["sensu"]["init_style"] = 'sysv'

sensu     3318     1  0 14:06 ?        00:00:00 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-server -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-server.pid -l /var/log/sensu/sensu-server.log -L warn
3. Verify the the log

cat /var/log/sensu/sensu-server | grep info
## Context

Output huge amount of unnecessary "info" log data.
## Your Environment

- Version of this cookbook used: 2.11.0
- Version of Sensu used: 0.20.6
- Version of Chef used: 12.6.0
- Operating System and version (e.g. CentOS 7, Ubuntu 14.04): CentOS 7
- Link to your project:

**Comment by cwjohnston** [comment]
Hi @JibinZheng, thanks for reporting this issue. I believe this is actually an oversight in the [runit script](https://github.com/sensu/sensu-build/blob/master/runit_scripts/sensu-sv-run.sh.erb) in the sensu-build project, which are not managed by this cookbook.

As described in https://github.com/sensu/sensu-omnibus/issues/34, Sensu 0.27 will be dropping support for the embedded runit service supervisor. As a result I think it's unlikely that this will be fixed in sensu-build, which is being replaced with omnibus-based builds (see https://github.com/sensu/sensu-omnibus). 

As far as this cookbook is concerned, I am going to close this issue as "wont fix" because the cookbook currently doesn't manage these runit scripts, and we are [deprecating the embedded runit](https://github.com/sensu/sensu-chef/pull/516) as well.
