### ISSUE TITLE
Remediation not defined in check provider

### ISSUE THREAD

**Issue by bobhlo** [sensu/sensu-chef#566]
## Expected Behavior

When attribute `remediation` defined in data bag, it should be populated in the check definition on sensu server

Attribute `remediation` should be populated in the check definition
## Possible Solution

Add attribute `remediation` to check provider - https://github.com/sensu/sensu-chef/blob/develop/providers/check.rb#L16-L19
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version of this cookbook used:4.0.0
* Version of Sensu used:0.28.5
* Version of Chef used:12.19.36
* Operating System and version (e.g. CentOS 7, Ubuntu 14.04):Ubuntu14.04
* Link to your project:

**Comment by cwjohnston** [comment]
@bobhlo because `remediation` is a custom check attribute, i.e. not defined in [the Sensu check attributes specification](https://sensuapp.org/docs/latest/reference/checks#check-attributes), we will not be adding it as a first-class attribute in the `sensu_check` provider.

I understand that you are asking that this be implemented in order to better support generating `sensu_check` resources from checks defined in a data bag items. Instead I suggest that you use Ruby logic to ensure that custom attributes, like `remediation`, are passed as a hash to the `sensu_check` resource's `additional` attribute. 

Here's an untested example of what I think the implementation would look like:

```ruby
data_bag(checks_data_bag).each do |data_bag_item|
  check = data_bag_item(checks_data_bag, data_bag_item)
  custom_attrs = Hash.new
  sensu_check check["id"] do
    check.each do |key, value|
      if respond_to?(key.to_sym)
         send(key.to_sym, value)
      else
          custom_attrs.merge!(key => value)
      end
      additional custom_attrs
    end
  end
end
```
