### ISSUE TITLE
Use the new repos

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-chef#573]
Per: https://blog.sensuapp.org/deprecated-sensu-repositories-to-be-shut-down-52928d82fa2e we should be using the new repo
## Expected Behavior
New users get new repos, pinned cookbooks remain unaffected.

## Current Behavior
All users get old repo by default

## Possible Solution
Update to use new URLs with a breaking change to be safe.

## Context
https://blog.sensuapp.org/deprecated-sensu-repositories-to-be-shut-down-52928d82fa2e

I am more than happy to submit a PR for this.

**Comment by cwjohnston** [comment]
Up to this point I haven't been actively pushing for this change everywhere because not all platforms have full support for Server Name Indication or accepting subjectAltName when verifying certificates.

Those concerns aside, this seems reasonable to me. I think we'll need to ensure that `apt-transport-https` package is installed on Debian/Ubuntu. Not sure if there are similar concerns with regard to older RedHat derivatives.

**Comment by cwjohnston** [comment]
Oops, I misunderstood which blogpost we're talking about, but my comment re: `apt-transport-https` stands.

In this more recent post we announced updates to the existing repositories.sensuapp.org repositories: https://blog.sensuapp.org/announcement-sensu-core-repositories-adding-https-ipv6-and-http-2-support-8480005b5ea4

These changes mean that https://repositories.sensuapp.org should now work, provided the platform in question supports SNI or certificate subjectAltName.

**Comment by majormoses** [comment]
Bringing the outcome of the conversation in slack here. The repos used are the correct repos, the install documentation should be updated to reflect this. Between the blog post I referenced and the documentation matching I assumed that this needed change when it appears to be the other way around.
