### ISSUE TITLE
Amazon Linux 2 support

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-chef#596]
I'd guess there are some things that we need to adjust to properly support amazon2 as this moves to systemd which is the thing that I expect will break things, there probably needs to be some omnibus work done first but we need to consider all the times we check platform family and similar here.

https://aws.amazon.com/about-aws/whats-new/2017/12/introducing-amazon-linux-2

**Comment by tas50** [comment]
You can check node['init_package'] within your platform checks. On any system with systemd it'll be 'systemd'.

**Comment by majormoses** [comment]
That has been super unreliable on the whole, this is partially due to a couple of reasons:
- supporting multiple init systems: Ubuntu 14.04 has `systemd`, `upstart`, and `sys-v` installed but the default on 14.04 is `sys-v`
- related to above: there is no standard way to determine what pid 1 really is. 

See: https://github.com/chef/ohai/issues/917

**Comment by adhodgson1** [comment]
Not related to Sensu necessairily but I have checked several Chef cookbooks on AWS Linux2 and several of them brake due to the platform check.  I haven't had time to look into this further but just ran a few tests.  Currently I am getting stuff like this firing:

if node['platform_version'].to_i <= 5

This currently equates to true on AWS Linux2 so any cookbook that uses similar (and there seems to be quite a few) currently brakes.

Andrew.

**Comment by majormoses** [comment]
resolved in #614
